In [46]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

In [107]:
pd.set_option('display.max_columns', None)
k = 3

# 1. Loading training and test datasets

In [48]:
def load_data():
    df_train = pd.read_csv('tpcds_train_clean.csv')
    df_test = pd.read_csv('tpcds_test_clean.csv')
    
    return df_train, df_test

In [49]:
df_train, df_test = load_data()

In [50]:
# slicing dataframe along rows
df_train = df_train[0:1000]
df_test = df_test[0:1000]

In [51]:
df_train.shape

(1000, 18)

In [52]:
df_train.columns

Index(['TQ', 'TQ COUNT', 'TBSCAN', 'TBSCAN COUNT', 'SORT', 'SORT COUNT',
       'FILTER', 'FILTER COUNT', 'HS JOIN', 'HS JOIN COUNT', 'TEMP',
       'TEMP COUNT', 'GRPBY', 'GRPBY COUNT', 'UNIQUE', 'UNIQUE COUNT', 'db2',
       'actual'],
      dtype='object')

In [53]:
df_train.head()

,TQ,TQ COUNT,TBSCAN,TBSCAN COUNT,SORT,SORT COUNT,FILTER,FILTER COUNT,HS JOIN,HS JOIN COUNT,TEMP,TEMP COUNT,GRPBY,GRPBY COUNT,UNIQUE,UNIQUE COUNT,db2,actual
0,2.890211,4.477836,-0.109936,-0.631929,-0.230971,-0.412469,-0.374475,-0.491027,-0.203300,-0.515257,-0.507391,0.069110,-0.374357,-0.683191,-0.308535,0.848438,72.568,117.012
1,-0.096758,-0.223322,-0.550475,-0.631929,-0.233063,-0.412469,1.128013,1.235810,-0.209978,-0.515257,-0.302987,-0.532953,-0.380635,-0.683191,-0.302633,-0.621787,82.636,323.176
2,-0.239077,-0.223322,0.626597,-0.111590,-0.233239,-0.412469,1.128023,1.235810,-0.070599,-0.028800,-0.506675,0.069110,3.919395,0.529035,-0.302633,-0.621787,1075.884,1874.272
3,-0.239077,-0.223322,-0.116630,-0.978821,-0.233063,-0.412469,-0.376033,-0.491027,-0.014063,-0.758486,-0.507415,-0.532953,-0.389237,-0.683191,-0.308041,-0.621787,44.276,21.636
4,-0.239077,-0.223322,0.626597,-0.111590,-0.230710,0.714227,-0.230843,1.235810,-0.070600,-0.028800,-0.506675,0.069110,3.076806,0.529035,-0.308145,-0.621787,979.024,1860.684

In [54]:
df_test.shape

(1000, 18)

# Clustering

In [55]:
def get_clusters(k, data, km):
    X = data.drop(columns=['db2','actual']);
    if km != None:
        print('clustering test dataset')
        y_kmeans = km.predict(X)
        
    else:
        print('clustering train dataset')
        km = KMeans(n_clusters = k, 
                        init='k-means++', 
                        n_init=10, 
                        max_iter=300, 
                        random_state=0)
        km.fit(X)
        y_kmeans = km.predict(X)
        
    print('Distortion: %.2f' % km.inertia_)
    df_train = data.copy();
    df_train['cluster'] = np.nan
    for i,e in enumerate(y_kmeans):
        df_train['cluster'].loc[i] = e;
    
    df_train = 
    return km, df_train

# Workload

def create_workload(batch_size, data, k):
    df_data = data[['db2','actual','cluster']]
    df_data = pd.get_dummies(df_data, columns=['cluster'])
    for i in range(0,k):
        c_name = 'cluster_%d.0' % i
        if c_name not in df_data.columns:
            df_data[c_name] = 0
            
    df_batches = pd.DataFrame(columns=df_data.columns)

    # debug - check the output from np.linspace
    print(data.shape[0] - 1)
    print(data.shape[0])
    
    indices = np.linspace(0, data.shape[0]-1, data.shape[0], dtype=int)
    num_batches = int(np.floor(df_data.shape[0] / batch_size))
        
    for ibat in range(num_batches):
        start = (ibat * batch_size)
        end = (ibat * batch_size + batch_size) - 1
        print("start: ", start, "end:", end)
        
        ibat_Y = df_data.loc[indices[start:end], :]

        #df_batches = pd.concat([df_batches, ibat_Y.sum()], ignore_index=True)
        
        df_batches = df_batches.append(ibat_Y.sum(), ignore_index=True)
        
    return df_batches

In [ ]:


batch_size = 2

num_batches = int(np.floor(df_train_clusters.shape[0] / batch_size))
# num_batches - batch size is correct (checked)

first_index = 10
last_index = 12

df_train_clusters.loc[indices[first_index:last_index], :]

#for i in range(num_batches):
 #   first_index = i 

        
    #for ibat in range(num_batches):
    #    start = (ibat * batch_size)
    #    end = (ibat * batch_size + batch_size) - 1
    #    print("start: ", start, "end:", end)
        
    #    ibat_Y = df_data.loc[indices[start:end], :]

    #    #df_batches = pd.concat([df_batches, ibat_Y.sum()], ignore_index=True)
        
    #    df_batches = df_batches.append(ibat_Y.sum(), ignore_index=True)
        
    #return df_batches

In [ ]:
def create_workload(batch_size, data, k):
    # keeping only the columns that I need
    df_data = data[['db2','actual','cluster']]

    # 1-hot encode the cluster column
    df_data = pd.get_dummies(df_data, columns=['cluster'])
    
    # create a dataframe of workload batches
    df_batches = pd.DataFrame(columns=df_data.columns)

    # debug - check the output from np.linspace
    print(data.shape[0] - 1)
    print(data.shape[0])
    
    # the following line generate a list of integers between the range of 0 and data.shape[0]-1. It generates data.shape[0] number of integers. 
    # If the dataframe has 1000 records, the value of data.shape[0] is 1000. Now we'll be generating 1000 numbers in the range (0, 999).
    # data.shape[0] - 1 = 999. The 3rd parameter tells the function to generate 1000 numbers. 
    # the final parameter is the datatype of the output numbers
    indices = np.linspace(0, data.shape[0]-1, data.shape[0], dtype=int)

    # shuffle these numbers
    np.random.shuffle(indices)
    
    num_batches = int(np.floor(df_data.shape[0] / batch_size))
        
    for ibat in range(num_batches):
        start = (ibat * batch_size)
        end = (ibat * batch_size + batch_size) - 1
        print("start: ", start, "end:", end)
        
        ibat_Y = df_data.loc[indices[start:end], :]

        #df_batches = pd.concat([df_batches, ibat_Y.sum()], ignore_index=True)
        
        df_batches = df_batches.append(ibat_Y.sum(), ignore_index=True)
        
    return df_batches

# Create Workloads

In [121]:
#batch_sizes = [2, 3, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

# batch_sizes = [2, 3, 5]
batch_sizes = [2]

km, df_train_clusters = get_clusters(k, df_train, None)
km, df_test_clusters  = get_clusters(k, df_test, km)

df_train_clusters.head()

clustering train dataset
Distortion: 12344.61
clustering test dataset
Distortion: 12344.61

,TQ,TQ COUNT,TBSCAN,TBSCAN COUNT,SORT,SORT COUNT,FILTER,FILTER COUNT,HS JOIN,HS JOIN COUNT,TEMP,TEMP COUNT,GRPBY,GRPBY COUNT,UNIQUE,UNIQUE COUNT,db2,actual,cluster
0,2.890211,4.477836,-0.109936,-0.631929,-0.230971,-0.412469,-0.374475,-0.491027,-0.203300,-0.515257,-0.507391,0.069110,-0.374357,-0.683191,-0.308535,0.848438,72.568,117.012,2.0
1,-0.096758,-0.223322,-0.550475,-0.631929,-0.233063,-0.412469,1.128013,1.235810,-0.209978,-0.515257,-0.302987,-0.532953,-0.380635,-0.683191,-0.302633,-0.621787,82.636,323.176,1.0
2,-0.239077,-0.223322,0.626597,-0.111590,-0.233239,-0.412469,1.128023,1.235810,-0.070599,-0.028800,-0.506675,0.069110,3.919395,0.529035,-0.302633,-0.621787,1075.884,1874.272,1.0
3,-0.239077,-0.223322,-0.116630,-0.978821,-0.233063,-0.412469,-0.376033,-0.491027,-0.014063,-0.758486,-0.507415,-0.532953,-0.389237,-0.683191,-0.308041,-0.621787,44.276,21.636,1.0
4,-0.239077,-0.223322,0.626597,-0.111590,-0.230710,0.714227,-0.230843,1.235810,-0.070600,-0.028800,-0.506675,0.069110,3.076806,0.529035,-0.308145,-0.621787,979.024,1860.684,1.0

# TEST

In [156]:
batch_sizes = [2]

km, df_train_clusters = get_clusters(k, df_train, None)
df_train_clusters['cluster'] = df_train_clusters['cluster'].astype('int32')

#df_train_clusters = get_clusters(k, df_train, None)

# debugging create_workload function
#df_train_clusters.shape

df_train_clusters = df_train_clusters[['db2','actual','cluster']]

print(df_train_clusters.shape[0])

indices = np.linspace(0, df_train_clusters.shape[0]-1, df_train_clusters.shape[0], dtype=int)
#indices

# now shuffle the numbers in the array
np.random.shuffle(indices)
#indices - checked suffle

# better way to shuffle the dataframe
#print(df_train_clusters.head(5))
df_train_clusters = df_train_clusters.sample(frac=1, ignore_index=True)

#print(df_train_clusters.head(6))
#df_train_clusters['cluster'].value_counts()

# 1-hot encode the cluster column
#print(df_train_clusters.dtypes)
df_train_clusters = pd.get_dummies(df_train_clusters, columns=['cluster'])

print(df_train_clusters.dtypes)

# create a dataframe for the workloads
df_workloads = pd.DataFrame(columns=df_train_clusters.columns)
# check if the dataframe was created correctly
# print(df_workloads.head())
# CHECKED - OKAY

batch_size = 3

first_index = 0
last_index = 0 

for i in range(2):
    if i > 0:
        first_index = last_index + 1
    last_index = first_index + batch_size - 1

    # print indices range to ensure they are correct
    # print(first_index, " ", last_index)
    # CHECKED - OK

    df_temp = df_train_clusters.loc[first_index:last_index, :]

    df_workload = pd.DataFrame(columns=df_temp.columns)
    
    print(df_temp)

    #print(type(df_temp))

    # ref: https://stackoverflow.com/questions/69575967/pandas-new-dataframe-that-has-sum-of-columns-from-another
    df_workload = df_temp.sum(axis=0).to_frame().T

    #print(df_workload)

    df_workloads = pd.concat([df_workloads, df_workload], ignore_index=True)

print('All workloads:')
print(df_workloads)

clustering train dataset
Distortion: 12344.61
1000
db2          float64
actual       float64
cluster_0      uint8
cluster_1      uint8
cluster_2      uint8
dtype: object
       db2   actual  cluster_0  cluster_1  cluster_2
0  116.208  166.212          0          1          0
1  976.080  567.632          0          1          0
2  209.584  158.788          0          1          0
       db2    actual  cluster_0  cluster_1  cluster_2
3  315.884    83.728          0          1          0
4  597.420  1146.520          1          0          0
5  124.412   385.444          0          1          0
All workloads:
        db2    actual  cluster_0  cluster_1  cluster_2
0  1301.872   892.632        0.0        3.0        0.0
1  1037.716  1615.692        1.0        2.0        0.0

In [66]:
df_test_clusters.head()

,TQ,TQ COUNT,TBSCAN,TBSCAN COUNT,SORT,SORT COUNT,FILTER,FILTER COUNT,HS JOIN,HS JOIN COUNT,TEMP,TEMP COUNT,GRPBY,GRPBY COUNT,UNIQUE,UNIQUE COUNT,db2,actual,cluster
0,-0.240514,-0.223322,0.462542,-0.111590,-0.233275,-0.412469,-0.355816,-0.491027,-0.185196,0.214428,-0.468062,0.069110,-0.389239,-0.683191,-0.302955,0.848438,209.584,158.860,0.0
1,-0.240514,-0.223322,0.775236,0.061856,-0.233275,-0.412469,-0.376034,-0.491027,-0.142859,0.457657,-0.506034,0.671172,-0.389239,0.529035,3.263571,-0.621787,291.488,2618.864,0.0
2,-0.240514,-0.223322,0.619996,0.061856,-0.233275,-0.412469,3.328263,-0.491027,-0.187562,0.457657,4.665741,3.681484,-0.389239,-0.683191,-0.308535,-0.621787,242.508,228.172,1.0
3,-0.096758,-0.223322,-0.829048,-0.458483,-0.233063,-0.412469,-0.242231,-0.491027,-0.200314,-0.272029,-0.462133,-0.532953,-0.261471,-0.683191,-0.302150,0.848438,377.412,393.260,0.0
4,2.904989,4.477836,-0.109936,-0.631929,-0.230960,-0.412469,-0.374468,-0.491027,-0.203295,-0.515257,-0.507391,0.069110,-0.374286,-0.683191,-0.308535,0.848438,72.556,116.456,2.0

In [72]:
df_train_clusters['cluster'].value_counts()

0    738
3    137
2     66
4     31
1     28
Name: cluster, dtype: int64

In [73]:
df_train_clusters['cluster'] = df_train_clusters['cluster'].astype('int32')
df_test_clusters['cluster'] = df_test_clusters['cluster'].astype('int32')

In [68]:
for batch_size in batch_sizes:
    workload_train = create_workload(batch_size,df_train_clusters,k)
    workload_test = create_workload(batch_size,df_test_clusters,k)


    file_name_train = 'train_workloads_final_%s_clusters_%s_batch.csv' % (k, batch_size)
    file_name_test  = 'test_workloads_final_%s_clusters_%s_batch.csv' % (k, batch_size)
    workload_train.to_csv(file_name_train ,index=False)
    workload_test.to_csv(file_name_test ,index=False)
    print("batch = %s is done" % (batch_size))

999
1000
start:  0 end: 1
start:  2 end: 3
start:  4 end: 5
start:  6 end: 7
start:  8 end: 9
start:  10 end: 11
start:  12 end: 13
start:  14 end: 15
start:  16 end: 17
start:  18 end: 19
start:  20 end: 21
start:  22 end: 23
start:  24 end: 25
start:  26 end: 27
start:  28 end: 29
start:  30 end: 31
start:  32 end: 33
start:  34 end: 35
start:  36 end: 37
start:  38 end: 39
start:  40 end: 41
start:  42 end: 43
start:  44 end: 45
start:  46 end: 47
start:  48 end: 49
start:  50 end: 51
start:  52 end: 53
start:  54 end: 55
start:  56 end: 57
start:  58 end: 59
start:  60 end: 61
start:  62 end: 63
start:  64 end: 65
start:  66 end: 67
start:  68 end: 69
start:  70 end: 71
start:  72 end: 73
start:  74 end: 75
start:  76 end: 77
start:  78 end: 79
start:  80 end: 81
start:  82 end: 83
start:  84 end: 85
start:  86 end: 87
start:  88 end: 89
start:  90 end: 91
start:  92 end: 93
start:  94 end: 95
start:  96 end: 97
start:  98 end: 99
start:  100 end: 101
start:  102 end: 103
start:  104 end: 105
start:  106 end: 107
start:  108 end: 109
start:  110 end: 111
start:  112 end: 113
start:  114 end: 115
start:  116 end: 117
start:  118 end: 119
start:  120 end: 121
start:  122 end: 123
start:  124 end: 125
start:  126 end: 127
start:  128 end: 129
start:  130 end: 131
start:  132 end: 133
start:  134 end: 135
start:  136 end: 137
start:  138 end: 139
start:  140 end: 141
start:  142 end: 143
start:  144 end: 145
start:  146 end: 147
start:  148 end: 149
start:  150 end: 151
start:  152 end: 153
start:  154 end: 155
start:  156 end: 157
start:  158 end: 159
start:  160 end: 161
start:  162 end: 163
start:  164 end: 165
start:  166 end: 167
start:  168 end: 169
start:  170 end: 171
start:  172 end: 173
start:  174 end: 175
start:  176 end: 177
start:  178 end: 179
start:  180 end: 181
start:  182 end: 183
start:  184 end: 185
start:  186 end: 187
start:  188 end: 189
start:  190 end: 191
start:  192 end: 193
start:  194 end: 195
start:  196 end: 197
start:  198 end: 199
start:  200 end: 201
start:  202 end: 203
start:  204 end: 205
start:  206 end: 207
start:  208 end: 209
start:  210 end: 211
start:  212 end: 213
start:  214 end: 215
start:  216 end: 217
start:  218 end: 219
start:  220 end: 221
start:  222 end: 223
start:  224 end: 225
start:  226 end: 227
start:  228 end: 229
start:  230 end: 231
start:  232 end: 233
start:  234 end: 235
start:  236 end: 237
start:  238 end: 239
start:  240 end: 241
start:  242 end: 243
start:  244 end: 245
start:  246 end: 247
start:  248 end: 249
start:  250 end: 251
start:  252 end: 253
start:  254 end: 255
start:  256 end: 257
start:  258 end: 259
start:  260 end: 261
start:  262 end: 263
start:  264 end: 265
start:  266 end: 267
start:  268 end: 269
start:  270 end: 271
start:  272 end: 273
start:  274 end: 275
start:  276 end: 277
start:  278 end: 279
start:  280 end: 281
start:  282 end: 283
start:  284 end: 285
start:  286 end: 287
start:  288 end: 289
start:  290 end: 291
start:  292 end: 293
start:  294 end: 295
start:  296 end: 297
start:  298 end: 299
start:  300 end: 301
start:  302 end: 303
start:  304 end: 305
start:  306 end: 307
start:  308 end: 309
start:  310 end: 311
start:  312 end: 313
start:  314 end: 315
start:  316 end: 317
start:  318 end: 319
start:  320 end: 321
start:  322 end: 323
start:  324 end: 325
start:  326 end: 327
start:  328 end: 329
start:  330 end: 331
start:  332 end: 333
start:  334 end: 335
start:  336 end: 337
start:  338 end: 339
start:  340 end: 341
start:  342 end: 343
start:  344 end: 345
start:  346 end: 347
start:  348 end: 349
start:  350 end: 351
start:  352 end: 353
start:  354 end: 355
start:  356 end: 357
start:  358 end: 359
start:  360 end: 361
start:  362 end: 363
start:  364 end: 365
start:  366 end: 367
start:  368 end: 369
start:  370 end: 371
start:  372 end: 373
start:  374 end: 375
start:  376 end: 377
start:  378 end: 379
start:  380 end: 381
start:  382 end: 383
start:  384 end: 385
start:  386 end: 387
start:  388 end: 389
start:  390 end: 391
start:  392 end: 393
start:  394 end: 395
start:  396 end: 397
start:  398 end: 399
start:  400 end: 401
start:  402 end: 403
start:  404 end: 405
start:  406 end: 407
start:  408 end: 409
start:  410 end: 411
start:  412 end: 413
start:  414 end: 415
start:  416 end: 417
start:  418 end: 419
start:  420 end: 421
start:  422 end: 423
start:  424 end: 425
start:  426 end: 427
start:  428 end: 429
start:  430 end: 431
start:  432 end: 433
start:  434 end: 435
start:  436 end: 437
start:  438 end: 439
start:  440 end: 441
start:  442 end: 443
start:  444 end: 445
start:  446 end: 447
start:  448 end: 449
start:  450 end: 451
start:  452 end: 453
start:  454 end: 455
start:  456 end: 457
start:  458 end: 459
start:  460 end: 461
start:  462 end: 463
start:  464 end: 465
start:  466 end: 467
start:  468 end: 469
start:  470 end: 471
start:  472 end: 473
start:  474 end: 475
start:  476 end: 477
start:  478 end: 479
start:  480 end: 481
start:  482 end: 483
start:  484 end: 485
start:  486 end: 487
start:  488 end: 489
start:  490 end: 491
start:  492 end: 493
start:  494 end: 495
start:  496 end: 497
start:  498 end: 499
start:  500 end: 501
start:  502 end: 503
start:  504 end: 505
start:  506 end: 507
start:  508 end: 509
start:  510 end: 511
start:  512 end: 513
start:  514 end: 515
start:  516 end: 517
start:  518 end: 519
start:  520 end: 521
start:  522 end: 523
start:  524 end: 525
start:  526 end: 527
start:  528 end: 529
start:  530 end: 531
start:  532 end: 533
start:  534 end: 535
start:  536 end: 537
start:  538 end: 539
start:  540 end: 541
start:  542 end: 543
start:  544 end: 545
start:  546 end: 547
start:  548 end: 549
start:  550 end: 551
start:  552 end: 553
start:  554 end: 555
start:  556 end: 557
start:  558 end: 559
start:  560 end: 561
start:  562 end: 563
start:  564 end: 565
start:  566 end: 567
start:  568 end: 569
start:  570 end: 571
start:  572 end: 573
start:  574 end: 575
start:  576 end: 577
start:  578 end: 579
start:  580 end: 581
start:  582 end: 583
start:  584 end: 585
start:  586 end: 587
start:  588 end: 589
start:  590 end: 591
start:  592 end: 593
start:  594 end: 595
start:  596 end: 597
start:  598 end: 599
start:  600 end: 601
start:  602 end: 603
start:  604 end: 605
start:  606 end: 607
start:  608 end: 609
start:  610 end: 611
start:  612 end: 613
start:  614 end: 615
start:  616 end: 617
start:  618 end: 619
start:  620 end: 621
start:  622 end: 623
start:  624 end: 625
start:  626 end: 627
start:  628 end: 629
start:  630 end: 631
start:  632 end: 633
start:  634 end: 635
start:  636 end: 637
start:  638 end: 639
start:  640 end: 641
start:  642 end: 643
start:  644 end: 645
start:  646 end: 647
start:  648 end: 649
start:  650 end: 651
start:  652 end: 653
start:  654 end: 655
start:  656 end: 657
start:  658 end: 659
start:  660 end: 661
start:  662 end: 663
start:  664 end: 665
start:  666 end: 667
start:  668 end: 669
start:  670 end: 671
start:  672 end: 673
start:  674 end: 675
start:  676 end: 677
start:  678 end: 679
start:  680 end: 681
start:  682 end: 683
start:  684 end: 685
start:  686 end: 687
start:  688 end: 689
start:  690 end: 691
start:  692 end: 693
start:  694 end: 695
start:  696 end: 697
start:  698 end: 699
start:  700 end: 701
start:  702 end: 703
start:  704 end: 705
start:  706 end: 707
start:  708 end: 709
start:  710 end: 711
start:  712 end: 713
start:  714 end: 715
start:  716 end: 717
start:  718 end: 719
start:  720 end: 721
start:  722 end: 723
start:  724 end: 725
start:  726 end: 727
start:  728 end: 729
start:  730 end: 731
start:  732 end: 733
start:  734 end: 735
start:  736 end: 737
start:  738 end: 739
start:  740 end: 741
start:  742 end: 743
start:  744 end: 745
start:  746 end: 747
start:  748 end: 749
start:  750 end: 751
start:  752 end: 753
start:  754 end: 755
start:  756 end: 757
start:  758 end: 759
start:  760 end: 761
start:  762 end: 763
start:  764 end: 765
start:  766 end: 767
start:  768 end: 769
start:  770 end: 771
start:  772 end: 773
start:  774 end: 775
start:  776 end: 777
start:  778 end: 779
start:  780 end: 781
start:  782 end: 783
start:  784 end: 785
start:  786 end: 787
start:  788 end: 789
start:  790 end: 791
start:  792 end: 793
start:  794 end: 795
start:  796 end: 797
start:  798 end: 799
start:  800 end: 801
start:  802 end: 803
start:  804 end: 805
start:  806 end: 807
start:  808 end: 809
start:  810 end: 811
start:  812 end: 813
start:  814 end: 815
start:  816 end: 817
start:  818 end: 819
start:  820 end: 821
start:  822 end: 823
start:  824 end: 825
start:  826 end: 827
start:  828 end: 829
start:  830 end: 831
start:  832 end: 833
start:  834 end: 835
start:  836 end: 837
start:  838 end: 839
start:  840 end: 841
start:  842 end: 843
start:  844 end: 845
start:  846 end: 847
start:  848 end: 849
start:  850 end: 851
start:  852 end: 853
start:  854 end: 855
start:  856 end: 857
start:  858 end: 859
start:  860 end: 861
start:  862 end: 863
start:  864 end: 865
start:  866 end: 867
start:  868 end: 869
start:  870 end: 871
start:  872 end: 873
start:  874 end: 875
start:  876 end: 877
start:  878 end: 879
start:  880 end: 881
start:  882 end: 883
start:  884 end: 885
start:  886 end: 887
start:  888 end: 889
start:  890 end: 891
start:  892 end: 893
start:  894 end: 895
start:  896 end: 897
start:  898 end: 899
start:  900 end: 901
start:  902 end: 903
start:  904 end: 905
start:  906 end: 907
start:  908 end: 909
start:  910 end: 911
start:  912 end: 913
start:  914 end: 915
start:  916 end: 917
start:  918 end: 919
start:  920 end: 921
start:  922 end: 923
start:  924 end: 925
start:  926 end: 927
start:  928 end: 929
start:  930 end: 931
start:  932 end: 933
start:  934 end: 935
start:  936 end: 937
start:  938 end: 939
start:  940 end: 941
start:  942 end: 943
start:  944 end: 945
start:  946 end: 947
start:  948 end: 949
start:  950 end: 951
start:  952 end: 953
start:  954 end: 955
start:  956 end: 957
start:  958 end: 959
start:  960 end: 961
start:  962 end: 963
start:  964 end: 965
start:  966 end: 967
start:  968 end: 969
start:  970 end: 971
start:  972 end: 973
start:  974 end: 975
start:  976 end: 977
start:  978 end: 979
start:  980 end: 981
start:  982 end: 983
start:  984 end: 985
start:  986 end: 987
start:  988 end: 989
start:  990 end: 991
start:  992 end: 993
start:  994 end: 995
start:  996 end: 997
start:  998 end: 999
999
1000
start:  0 end: 1
start:  2 end: 3
start:  4 end: 5
start:  6 end: 7
start:  8 end: 9
start:  10 end: 11
start:  12 end: 13
start:  14 end: 15
start:  16 end: 17
start:  18 end: 19
start:  20 end: 21
start:  22 end: 23
start:  24 end: 25
start:  26 end: 27
start:  28 end: 29
start:  30 end: 31
start:  32 end: 33
start:  34 end: 35
start:  36 end: 37
start:  38 end: 39
start:  40 end: 41
start:  42 end: 43
start:  44 end: 45
start:  46 end: 47
start:  48 end: 49
start:  50 end: 51
start:  52 end: 53
start:  54 end: 55
start:  56 end: 57
start:  58 end: 59
start:  60 end: 61
start:  62 end: 63
start:  64 end: 65
start:  66 end: 67
start:  68 end: 69
start:  70 end: 71
start:  72 end: 73
start:  74 end: 75
start:  76 end: 77
start:  78 end: 79
start:  80 end: 81
start:  82 end: 83
start:  84 end: 85
start:  86 end: 87
start:  88 end: 89
start:  90 end: 91
start:  92 end: 93
start:  94 end: 95
start:  96 end: 97
start:  98 end: 99
start:  100 end: 101
start:  102 end: 103
start:  104 end: 105
start:  106 end: 107
start:  108 end: 109
start:  110 end: 111
start:  112 end: 113
start:  114 end: 115
start:  116 end: 117
start:  118 end: 119
start:  120 end: 121
start:  122 end: 123
start:  124 end: 125
start:  126 end: 127
start:  128 end: 129
start:  130 end: 131
start:  132 end: 133
start:  134 end: 135
start:  136 end: 137
start:  138 end: 139
start:  140 end: 141
start:  142 end: 143
start:  144 end: 145
start:  146 end: 147
start:  148 end: 149
start:  150 end: 151
start:  152 end: 153
start:  154 end: 155
start:  156 end: 157
start:  158 end: 159
start:  160 end: 161
start:  162 end: 163
start:  164 end: 165
start:  166 end: 167
start:  168 end: 169
start:  170 end: 171
start:  172 end: 173
start:  174 end: 175
start:  176 end: 177
start:  178 end: 179
start:  180 end: 181
start:  182 end: 183
start:  184 end: 185
start:  186 end: 187
start:  188 end: 189
start:  190 end: 191
start:  192 end: 193
start:  194 end: 195
start:  196 end: 197
start:  198 end: 199
start:  200 end: 201
start:  202 end: 203
start:  204 end: 205
start:  206 end: 207
start:  208 end: 209
start:  210 end: 211
start:  212 end: 213
start:  214 end: 215
start:  216 end: 217
start:  218 end: 219
start:  220 end: 221
start:  222 end: 223
start:  224 end: 225
start:  226 end: 227
start:  228 end: 229
start:  230 end: 231
start:  232 end: 233
start:  234 end: 235
start:  236 end: 237
start:  238 end: 239
start:  240 end: 241
start:  242 end: 243
start:  244 end: 245
start:  246 end: 247
start:  248 end: 249
start:  250 end: 251
start:  252 end: 253
start:  254 end: 255
start:  256 end: 257
start:  258 end: 259
start:  260 end: 261
start:  262 end: 263
start:  264 end: 265
start:  266 end: 267
start:  268 end: 269
start:  270 end: 271
start:  272 end: 273
start:  274 end: 275
start:  276 end: 277
start:  278 end: 279
start:  280 end: 281
start:  282 end: 283
start:  284 end: 285
start:  286 end: 287
start:  288 end: 289
start:  290 end: 291
start:  292 end: 293
start:  294 end: 295
start:  296 end: 297
start:  298 end: 299
start:  300 end: 301
start:  302 end: 303
start:  304 end: 305
start:  306 end: 307
start:  308 end: 309
start:  310 end: 311
start:  312 end: 313
start:  314 end: 315
start:  316 end: 317
start:  318 end: 319
start:  320 end: 321
start:  322 end: 323
start:  324 end: 325
start:  326 end: 327
start:  328 end: 329
start:  330 end: 331
start:  332 end: 333
start:  334 end: 335
start:  336 end: 337
start:  338 end: 339
start:  340 end: 341
start:  342 end: 343
start:  344 end: 345
start:  346 end: 347
start:  348 end: 349
start:  350 end: 351
start:  352 end: 353
start:  354 end: 355
start:  356 end: 357
start:  358 end: 359
start:  360 end: 361
start:  362 end: 363
start:  364 end: 365
start:  366 end: 367
start:  368 end: 369
start:  370 end: 371
start:  372 end: 373
start:  374 end: 375
start:  376 end: 377
start:  378 end: 379
start:  380 end: 381
start:  382 end: 383
start:  384 end: 385
start:  386 end: 387
start:  388 end: 389
start:  390 end: 391
start:  392 end: 393
start:  394 end: 395
start:  396 end: 397
start:  398 end: 399
start:  400 end: 401
start:  402 end: 403
start:  404 end: 405
start:  406 end: 407
start:  408 end: 409
start:  410 end: 411
start:  412 end: 413
start:  414 end: 415
start:  416 end: 417
start:  418 end: 419
start:  420 end: 421
start:  422 end: 423
start:  424 end: 425
start:  426 end: 427
start:  428 end: 429
start:  430 end: 431
start:  432 end: 433
start:  434 end: 435
start:  436 end: 437
start:  438 end: 439
start:  440 end: 441
start:  442 end: 443
start:  444 end: 445
start:  446 end: 447
start:  448 end: 449
start:  450 end: 451
start:  452 end: 453
start:  454 end: 455
start:  456 end: 457
start:  458 end: 459
start:  460 end: 461
start:  462 end: 463
start:  464 end: 465
start:  466 end: 467
start:  468 end: 469
start:  470 end: 471
start:  472 end: 473
start:  474 end: 475
start:  476 end: 477
start:  478 end: 479
start:  480 end: 481
start:  482 end: 483
start:  484 end: 485
start:  486 end: 487
start:  488 end: 489
start:  490 end: 491
start:  492 end: 493
start:  494 end: 495
start:  496 end: 497
start:  498 end: 499
start:  500 end: 501
start:  502 end: 503
start:  504 end: 505
start:  506 end: 507
start:  508 end: 509
start:  510 end: 511
start:  512 end: 513
start:  514 end: 515
start:  516 end: 517
start:  518 end: 519
start:  520 end: 521
start:  522 end: 523
start:  524 end: 525
start:  526 end: 527
start:  528 end: 529
start:  530 end: 531
start:  532 end: 533
start:  534 end: 535
start:  536 end: 537
start:  538 end: 539
start:  540 end: 541
start:  542 end: 543
start:  544 end: 545
start:  546 end: 547
start:  548 end: 549
start:  550 end: 551
start:  552 end: 553
start:  554 end: 555
start:  556 end: 557
start:  558 end: 559
start:  560 end: 561
start:  562 end: 563
start:  564 end: 565
start:  566 end: 567
start:  568 end: 569
start:  570 end: 571
start:  572 end: 573
start:  574 end: 575
start:  576 end: 577
start:  578 end: 579
start:  580 end: 581
start:  582 end: 583
start:  584 end: 585
start:  586 end: 587
start:  588 end: 589
start:  590 end: 591
start:  592 end: 593
start:  594 end: 595
start:  596 end: 597
start:  598 end: 599
start:  600 end: 601
start:  602 end: 603
start:  604 end: 605
start:  606 end: 607
start:  608 end: 609
start:  610 end: 611
start:  612 end: 613
start:  614 end: 615
start:  616 end: 617
start:  618 end: 619
start:  620 end: 621
start:  622 end: 623
start:  624 end: 625
start:  626 end: 627
start:  628 end: 629
start:  630 end: 631
start:  632 end: 633
start:  634 end: 635
start:  636 end: 637
start:  638 end: 639
start:  640 end: 641
start:  642 end: 643
start:  644 end: 645
start:  646 end: 647
start:  648 end: 649
start:  650 end: 651
start:  652 end: 653
start:  654 end: 655
start:  656 end: 657
start:  658 end: 659
start:  660 end: 661
start:  662 end: 663
start:  664 end: 665
start:  666 end: 667
start:  668 end: 669
start:  670 end: 671
start:  672 end: 673
start:  674 end: 675
start:  676 end: 677
start:  678 end: 679
start:  680 end: 681
start:  682 end: 683
start:  684 end: 685
start:  686 end: 687
start:  688 end: 689
start:  690 end: 691
start:  692 end: 693
start:  694 end: 695
start:  696 end: 697
start:  698 end: 699
start:  700 end: 701
start:  702 end: 703
start:  704 end: 705
start:  706 end: 707
start:  708 end: 709
start:  710 end: 711
start:  712 end: 713
start:  714 end: 715
start:  716 end: 717
start:  718 end: 719
start:  720 end: 721
start:  722 end: 723
start:  724 end: 725
start:  726 end: 727
start:  728 end: 729
start:  730 end: 731
start:  732 end: 733
start:  734 end: 735
start:  736 end: 737
start:  738 end: 739
start:  740 end: 741
start:  742 end: 743
start:  744 end: 745
start:  746 end: 747
start:  748 end: 749
start:  750 end: 751
start:  752 end: 753
start:  754 end: 755
start:  756 end: 757
start:  758 end: 759
start:  760 end: 761
start:  762 end: 763
start:  764 end: 765
start:  766 end: 767
start:  768 end: 769
start:  770 end: 771
start:  772 end: 773
start:  774 end: 775
start:  776 end: 777
start:  778 end: 779
start:  780 end: 781
start:  782 end: 783
start:  784 end: 785
start:  786 end: 787
start:  788 end: 789
start:  790 end: 791
start:  792 end: 793
start:  794 end: 795
start:  796 end: 797
start:  798 end: 799
start:  800 end: 801
start:  802 end: 803
start:  804 end: 805
start:  806 end: 807
start:  808 end: 809
start:  810 end: 811
start:  812 end: 813
start:  814 end: 815
start:  816 end: 817
start:  818 end: 819
start:  820 end: 821
start:  822 end: 823
start:  824 end: 825
start:  826 end: 827
start:  828 end: 829
start:  830 end: 831
start:  832 end: 833
start:  834 end: 835
start:  836 end: 837
start:  838 end: 839
start:  840 end: 841
start:  842 end: 843
start:  844 end: 845
start:  846 end: 847
start:  848 end: 849
start:  850 end: 851
start:  852 end: 853
start:  854 end: 855
start:  856 end: 857
start:  858 end: 859
start:  860 end: 861
start:  862 end: 863
start:  864 end: 865
start:  866 end: 867
start:  868 end: 869
start:  870 end: 871
start:  872 end: 873
start:  874 end: 875
start:  876 end: 877
start:  878 end: 879
start:  880 end: 881
start:  882 end: 883
start:  884 end: 885
start:  886 end: 887
start:  888 end: 889
start:  890 end: 891
start:  892 end: 893
start:  894 end: 895
start:  896 end: 897
start:  898 end: 899
start:  900 end: 901
start:  902 end: 903
start:  904 end: 905
start:  906 end: 907
start:  908 end: 909
start:  910 end: 911
start:  912 end: 913
start:  914 end: 915
start:  916 end: 917
start:  918 end: 919
start:  920 end: 921
start:  922 end: 923